[directory]
truncate_to_repo = true
truncation_symbol = ".../"
truncation_length = 5

[kubernetes]
disabled = false
[kubernetes.context_aliases]
'^arn:(?P<Partition>[^:\n]*):(?P<Service>[^:\n]*):(?P<Region>[^:\n]*):(?P<AccountID>[^:\n]*):(?P<Ignore>(?P<ResourceType>[^:\\/\n]*)[:\\/])?(?P<Resource>.*)$' = '${Resource}-${Region}'

[time]
format = '[ $time ]($style) '
disabled = false

[status]
disabled = false

[memory_usage]
disabled = false
threshold = -1
format="via $symbol [${ram}]($style) "

[custom.aws-account]
command = "echo $CLOUD_IDENTIFIER"  # shows output of command
when = """ test $CLOUD_IDENTIFIER """
symbol = ""
format = 'for [$symbol $output]($style) '

